### PR TITLE
Add compact player controls and support for custom wrapped components

### PR DESCRIPTION
**Pull request by Abbondanzo**
Adds a few new features

- Adds compact controls that provide the same functionality as the standard set of controls provide.
- New compact view tab to testing page
- Optional `autoplay` prop added to replay viewer that will start or stop the clock on mount
- Caches requests for position data to prevent duplicate requests

Fixes a few bugs as well:

- Fixes a bug where the objects that spawn in the scene don't take their correct positions
- Fixes a bug where the "play" button doesn't match the initial state of the viewer

### CODE REVIEW

**Comment by dtracers** [comment]
Cool looks good!
Am slightly confused on how custom wrapped components work but looks great!

**Comment by Abbondanzo** [comment]
@dtracers 

>Am slightly confused on how custom wrapped components work but looks great!

Which wrapped components?

**Comment by dtracers** [comment]
I am taking this from your title
> and support for custom wrapped components

**Comment by Abbondanzo** [comment]
Ah. The `ReplayViewer` can wrap children that you want to render inside of the fullscreen view. So you can do this now

```jsx
<ReplayViewer>
  <MyCustomComponent />
</ReplayViewer>
```

**Pull request merged**
